### PR TITLE
Deployment

### PR DESCRIPTION
**Pull request by RohanRusta21**
Hi ,

I have found this issue while executing your docker Image. I have also added Service.yaml with NodePort type.

image

### CODE REVIEW

**Comment by rohanmaharjan100** [comment]
Thank you very much @RohanRusta21 . Could you show me the command you used to execute docker image.
Please use  --url flag   ` --url https://www.example_url.com` .
Eg: `docker run image_name --url https://www.facebook.com`

**Comment by rohanmaharjan100** [comment]
so , have you deployed this application in minikube?

**Comment by RohanRusta21** [comment]
Hi @rohanmaharjan100 yes I have deployed it but I was getting crashloopbackoff error. Can we connect in google meet or somewhere in EOD around 9:30 pm IST ? We can connect and deploy it together.

**Comment by rohanmaharjan100** [comment]
Hmm, sounds good.

**Comment by RohanRusta21** [comment]
Hi @rohanmaharjan100 I have modified Deployment.yaml and now application is deployed and working fine.

Please FInd Below Images: 

image

image

image

**Review by rohanmaharjan100 — APPROVED** [review]

**Pull request merged**
